// Code generated by protoc-gen-go from "feature.proto"
// DO NOT EDIT!

package proto

import proto1 "code.google.com/p/goprotobuf/proto"
import "math"

// Reference proto and math imports to suppress error if they are not otherwise used.
var _ = proto1.GetString
var _ = math.Inf

type Feature struct {
	Name             *string        `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	State            *Feature_State `protobuf:"bytes,2,req,name=state" json:"state,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (this *Feature) Reset()         { *this = Feature{} }
func (this *Feature) String() string { return proto1.CompactTextString(this) }
func (*Feature) ProtoMessage()       {}

type Feature_State struct {
	Type             *string `protobuf:"bytes,1,req,name=type" json:"type,omitempty"`
	Value            *string `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *Feature_State) Reset()         { *this = Feature_State{} }
func (this *Feature_State) String() string { return proto1.CompactTextString(this) }
func (*Feature_State) ProtoMessage()       {}

func init() {
}
