// Code generated by protoc-gen-go from "recipe.proto"
// DO NOT EDIT!

package proto

import proto1 "code.google.com/p/goprotobuf/proto"
import "math"

// Reference proto and math imports to suppress error if they are not otherwise used.
var _ = proto1.GetString
var _ = math.Inf

type Recipe struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Files            []*File `protobuf:"bytes,2,rep,name=files" json:"files,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *Recipe) Reset()         { *this = Recipe{} }
func (this *Recipe) String() string { return proto1.CompactTextString(this) }
func (*Recipe) ProtoMessage()       {}

func init() {
}
