GRAMMAR:

script		::	statement*

statement	::	'@import' path
		      |	  <var> '=' term
		      |	  <id> arglist block

path		  ::	<word>
		      |	  <string>

arglist		::	'(' args? ')'

args		  ::	arg ( ',' arg )*

arg		    ::	term
		      |	  <kwd> term

term		  ::	<string>
		      |	  <regexp>
		      |	  <var>
		      |	  <id> arglist

block		  ::	( '{' script '}' )?


LEXICAL RULES:

<word>		::	\S+			(block of non-whitespace)

<string>	::	"(\\.|[^"\\])*"		(double quoted strings)
		      |	  '(\\.|[^'\\])*'		(single quoted strings)

<regexp>	::	\/(\\.|[^\/\\])*\/[imxouesn]*	(Ruby regexes)

<var>		  ::	\$\w+			('$' + the usual)

<id>		  ::	\$|[_a-zA-Z]\w*		(the usual, or '$')

<kwd>		  ::	[a-zA-Z_:][-\w:.]*:	(XML attributes << ':')

<comment>	::	#.*			(single line)
		      |	  '#[' thru matching ']#'	(multiline, matched/nested)