GET /products/submarine HTTP/1.1
Host: m.example.com
Connection: keep-alive
User-Agent: Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_6; en-US) AppleWebKit/534.16 (KHTML, like Gecko) Chrome/10.0.648.133 Safari/534.16
Referer: http://m.example.com/expensive_gifts
Origin: http://m.example.com