POST /login HTTP/1.0
Host: MODaccounts.craigslist.orgMOD
User-Agent: Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.6; en-US; rv:1.9.1.17) Gecko/20110121 Firefox/3.5.17
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-us,en;q=0.5
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Keep-Alive: 300
Connection: close
Referer: MODhttp://accounts.craigslist.org/loginMOD
Cookie: cl_b=126729899192059858; cl_def_lang=en; cl_def_hp=sfbay
Content-Type: application/x-www-form-urlencoded
Content-Length: 107
Via: 1.0 moovweb