// Code generated by protoc-gen-go from "recipe.proto"
// DO NOT EDIT!

package hermes

import proto "goprotobuf.googlecode.com/hg/proto"
import "math"
import "os"

// Reference proto, math & os imports to suppress error if they are not otherwise used.
var _ = proto.GetString
var _ = math.Inf
var _ os.Error

type Recipe struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Files            []*File `protobuf:"bytes,2,rep,name=files" json:"files,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *Recipe) Reset()         { *this = Recipe{} }
func (this *Recipe) String() string { return proto.CompactTextString(this) }

func init() {
}
