// Code generated by protoc-gen-go from "package.proto"
// DO NOT EDIT!

package hermes

import proto "goprotobuf.googlecode.com/hg/proto"
import "math"
import "os"

// Reference proto, math & os imports to suppress error if they are not otherwise used.
var _ = proto.GetString
var _ = math.Inf
var _ os.Error

type Package struct {
	Name             *string  `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Version          *string  `protobuf:"bytes,2,req,name=version" json:"version,omitempty"`
	Package          [][]byte `protobuf:"bytes,3,rep,name=package" json:"package,omitempty"`
	XXX_unrecognized []byte   `json:",omitempty"`
}

func (this *Package) Reset()         { *this = Package{} }
func (this *Package) String() string { return proto.CompactTextString(this) }

func init() {
}
