GET /faq/ HTTP/1.0
Host: MODm.www.example.comMOD
Connection: close
Accept-Language: en-US,en;q=0.8
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.3
Via: 1.0 fred, 1.1 nowhere.com (Apache/1.1), 1.0 moovweb
If-Modified-Since: Mon, 14 Mar 2011 01:33:15 GMT