$a = concat("a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a")
$a = concat($a, $a, $a, $a) 
$a = concat($a, $a, $a, $a) 
$a = concat($a, $a, $a, $a) 
set($a)