// Code generated by protoc-gen-go from "package.proto"
// DO NOT EDIT!

package tritium

import proto "goprotobuf.googlecode.com/hg/proto"
import "math"
import "os"

// Reference proto, math & os imports to suppress error if they are not otherwise used.
var _ = proto.GetString
var _ = math.Inf
var _ os.Error

type Type struct {
	Name             *string `protobuf:"bytes,1,opt,name=name" json:"name"`
	XXX_unrecognized []byte
}

func (this *Type) Reset()         { *this = Type{} }
func (this *Type) String() string { return proto.CompactTextString(this) }

type Package struct {
	Name                  *string     `protobuf:"bytes,1,req,name=name" json:"name"`
	Functions             []*Function `protobuf:"bytes,2,rep,name=functions" json:"functions"`
	Types                 []*Type     `protobuf:"bytes,3,rep,name=types" json:"types"`
	DependentPackageNames []string    `protobuf:"bytes,4,rep,name=dependent_package_names" json:"dependent_package_names"`
	XXX_unrecognized      []byte
}

func (this *Package) Reset()         { *this = Package{} }
func (this *Package) String() string { return proto.CompactTextString(this) }

func init() {
}
