// Code generated by protoc-gen-go.
// source: credential.proto
// DO NOT EDIT!

package proto

import proto1 "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto1.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Credential struct {
	User             *string `protobuf:"bytes,1,req,name=user" json:"user,omitempty"`
	Password         *string `protobuf:"bytes,2,req,name=password" json:"password,omitempty"`
	Base64           *string `protobuf:"bytes,3,req,name=base64" json:"base64,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *Credential) Reset()         { *this = Credential{} }
func (this *Credential) String() string { return proto1.CompactTextString(this) }
func (*Credential) ProtoMessage()       {}

func (this *Credential) GetUser() string {
	if this != nil && this.User != nil {
		return *this.User
	}
	return ""
}

func (this *Credential) GetPassword() string {
	if this != nil && this.Password != nil {
		return *this.Password
	}
	return ""
}

func (this *Credential) GetBase64() string {
	if this != nil && this.Base64 != nil {
		return *this.Base64
	}
	return ""
}

func init() {
}
