// Code generated by protoc-gen-go.
// source: credentials.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	credentials.proto
	file.proto
	function.proto
	instruction.proto
	mixer.proto
	object.proto
	package.proto
	rewriter.proto
	rewrite_rule.proto
	slug.proto
	tritium.proto

It has these top-level messages:
	Credentials
*/
package proto

import proto1 "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto1.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Credentials struct {
	User             *string `protobuf:"bytes,1,req,name=user" json:"user,omitempty"`
	Password         *string `protobuf:"bytes,2,req,name=password" json:"password,omitempty"`
	Base64           *string `protobuf:"bytes,3,req,name=base64" json:"base64,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Credentials) Reset()         { *m = Credentials{} }
func (m *Credentials) String() string { return proto1.CompactTextString(m) }
func (*Credentials) ProtoMessage()    {}

func (m *Credentials) GetUser() string {
	if m != nil && m.User != nil {
		return *m.User
	}
	return ""
}

func (m *Credentials) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *Credentials) GetBase64() string {
	if m != nil && m.Base64 != nil {
		return *m.Base64
	}
	return ""
}

func init() {
}
