// Code generated by protoc-gen-go from "file.proto"
// DO NOT EDIT!

package proto

import proto1 "code.google.com/p/goprotobuf/proto"
import "math"

// Reference proto and math imports to suppress error if they are not otherwise used.
var _ = proto1.Marshal
var _ = math.Inf

type File struct {
	Path             *string `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
	Data             []byte  `protobuf:"bytes,2,req,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *File) Reset()         { *this = File{} }
func (this *File) String() string { return proto1.CompactTextString(this) }
func (*File) ProtoMessage()       {}

func (this *File) GetPath() string {
	if this != nil && this.Path != nil {
		return *this.Path
	}
	return ""
}

func (this *File) GetData() []byte {
	if this != nil {
		return this.Data
	}
	return nil
}

func init() {
}
