// Code generated by protoc-gen-go from "mixer.proto"
// DO NOT EDIT!

package proto

import proto1 "code.google.com/p/goprotobuf/proto"
import "math"

// Reference proto and math imports to suppress error if they are not otherwise used.
var _ = proto1.GetString
var _ = math.Inf

type Mixer struct {
	Name             *string  `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Version          *string  `protobuf:"bytes,2,req,name=version" json:"version,omitempty"`
	Rewriters        []*File  `protobuf:"bytes,3,rep,name=rewriters" json:"rewriters,omitempty"`
	Package          *Package `protobuf:"bytes,4,opt,name=package" json:"package,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (this *Mixer) Reset()         { *this = Mixer{} }
func (this *Mixer) String() string { return proto1.CompactTextString(this) }
func (*Mixer) ProtoMessage()       {}

func init() {
}
