// Code generated by protoc-gen-go.
// source: mixer.proto
// DO NOT EDIT!

package proto

import proto1 "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto1.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Mixer struct {
	Name             *string  `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Version          *string  `protobuf:"bytes,2,req,name=version" json:"version,omitempty"`
	Rewriters        []*File  `protobuf:"bytes,3,rep,name=rewriters" json:"rewriters,omitempty"`
	Package          *Package `protobuf:"bytes,4,opt,name=package" json:"package,omitempty"`
	PackagingMethod  *int32   `protobuf:"varint,5,opt,name=packaging_method" json:"packaging_method,omitempty"`
	Dependencies     []string `protobuf:"bytes,6,rep,name=dependencies" json:"dependencies,omitempty"`
	IsTransformer    *bool    `protobuf:"varint,7,opt,name=is_transformer" json:"is_transformer,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (this *Mixer) Reset()         { *this = Mixer{} }
func (this *Mixer) String() string { return proto1.CompactTextString(this) }
func (*Mixer) ProtoMessage()       {}

func (this *Mixer) GetName() string {
	if this != nil && this.Name != nil {
		return *this.Name
	}
	return ""
}

func (this *Mixer) GetVersion() string {
	if this != nil && this.Version != nil {
		return *this.Version
	}
	return ""
}

func (this *Mixer) GetPackage() *Package {
	if this != nil {
		return this.Package
	}
	return nil
}

func (this *Mixer) GetPackagingMethod() int32 {
	if this != nil && this.PackagingMethod != nil {
		return *this.PackagingMethod
	}
	return 0
}

func (this *Mixer) GetIsTransformer() bool {
	if this != nil && this.IsTransformer != nil {
		return *this.IsTransformer
	}
	return false
}

func init() {
}
