// Code generated by protoc-gen-go from "rewriterule.proto"
// DO NOT EDIT!

package proto

import proto1 "code.google.com/p/goprotobuf/proto"
import "math"

// Reference proto and math imports to suppress error if they are not otherwise used.
var _ = proto1.Marshal
var _ = math.Inf

type RewriteRule struct {
	From             *string `protobuf:"bytes,1,opt,name=from" json:"from,omitempty"`
	To               *string `protobuf:"bytes,2,opt,name=to" json:"to,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *RewriteRule) Reset()         { *this = RewriteRule{} }
func (this *RewriteRule) String() string { return proto1.CompactTextString(this) }
func (*RewriteRule) ProtoMessage()       {}

func (this *RewriteRule) GetFrom() string {
	if this != nil && this.From != nil {
		return *this.From
	}
	return ""
}

func (this *RewriteRule) GetTo() string {
	if this != nil && this.To != nil {
		return *this.To
	}
	return ""
}

func init() {
}
