// Code generated by protoc-gen-go from "slug.proto"
// DO NOT EDIT!

package proto

import proto1 "code.google.com/p/goprotobuf/proto"
import "math"

// Reference proto and math imports to suppress error if they are not otherwise used.
var _ = proto1.GetString
var _ = math.Inf

type Slug struct {
	Customer         *string      `protobuf:"bytes,1,req,name=customer" json:"customer,omitempty"`
	Project          *string      `protobuf:"bytes,2,req,name=project" json:"project,omitempty"`
	Version          *string      `protobuf:"bytes,3,req,name=version" json:"version,omitempty"`
	Transformers     []*Transform `protobuf:"bytes,4,rep,name=transformers" json:"transformers,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (this *Slug) Reset()         { *this = Slug{} }
func (this *Slug) String() string { return proto1.CompactTextString(this) }
func (*Slug) ProtoMessage()       {}

func init() {
}
