// Code generated by protoc-gen-go.
// source: slug.proto
// DO NOT EDIT!

package proto

import proto1 "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto1.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Slug struct {
	Name             *string        `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Version          *string        `protobuf:"bytes,2,req,name=version" json:"version,omitempty"`
	Transformers     []*Transform   `protobuf:"bytes,3,rep,name=transformers" json:"transformers,omitempty"`
	Rrules           []*RewriteRule `protobuf:"bytes,4,rep,name=rrules" json:"rrules,omitempty"`
	SslWhitelist     []string       `protobuf:"bytes,5,rep,name=ssl_whitelist" json:"ssl_whitelist,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (this *Slug) Reset()         { *this = Slug{} }
func (this *Slug) String() string { return proto1.CompactTextString(this) }
func (*Slug) ProtoMessage()       {}

func (this *Slug) GetName() string {
	if this != nil && this.Name != nil {
		return *this.Name
	}
	return ""
}

func (this *Slug) GetVersion() string {
	if this != nil && this.Version != nil {
		return *this.Version
	}
	return ""
}

func init() {
}
