// Code generated by protoc-gen-go from "function.proto"
// DO NOT EDIT!

package tritium

import proto "goprotobuf.googlecode.com/hg/proto"
import "math"
import "os"

// Reference proto, math & os imports to suppress error if they are not otherwise used.
var _ = proto.GetString
var _ = math.Inf
var _ os.Error

type Function struct {
	Name             *string              `protobuf:"bytes,1,opt,name=name" json:"name"`
	ScopeTypeId      *int32               `protobuf:"varint,2,opt,name=scope_type_id" json:"scope_type_id"`
	ScopeType        *string              `protobuf:"bytes,8,opt,name=scope_type" json:"scope_type"`
	ReturnTypeId     *int32               `protobuf:"varint,3,opt,name=return_type_id" json:"return_type_id"`
	OpensTypeId      *int32               `protobuf:"varint,4,opt,name=opens_type_id" json:"opens_type_id"`
	BuiltIn          *bool                `protobuf:"varint,5,opt,name=built_in" json:"built_in"`
	Args             []*Function_Argument `protobuf:"bytes,6,rep,name=args" json:"args"`
	Instruction      *Instruction         `protobuf:"bytes,7,opt,name=instruction" json:"instruction"`
	XXX_unrecognized []byte
}

func (this *Function) Reset()         { *this = Function{} }
func (this *Function) String() string { return proto.CompactTextString(this) }

type Function_Argument struct {
	TypeId           *int32  `protobuf:"varint,1,opt,name=type_id" json:"type_id"`
	TypeString       *string `protobuf:"bytes,2,opt,name=type_string" json:"type_string"`
	Name             *string `protobuf:"bytes,3,opt,name=name" json:"name"`
	XXX_unrecognized []byte
}

func (this *Function_Argument) Reset()         { *this = Function_Argument{} }
func (this *Function_Argument) String() string { return proto.CompactTextString(this) }

func init() {
}
