// Code generated by protoc-gen-go from "object.proto"
// DO NOT EDIT!

package tritium

import proto "goprotobuf.googlecode.com/hg/proto"
import "math"
import "os"

// Reference proto, math & os imports to suppress error if they are not otherwise used.
var _ = proto.GetString
var _ = math.Inf
var _ os.Error

type ScriptObject struct {
	Name             *string      `protobuf:"bytes,1,opt,name=name,def=main" json:"name"`
	Root             *Instruction `protobuf:"bytes,2,opt,name=root" json:"root"`
	ScopeTypeId      *int32       `protobuf:"varint,3,opt,name=scope_type_id" json:"scope_type_id"`
	Linked           *bool        `protobuf:"varint,4,opt,name=linked" json:"linked"`
	XXX_unrecognized []byte
}

func (this *ScriptObject) Reset()         { *this = ScriptObject{} }
func (this *ScriptObject) String() string { return proto.CompactTextString(this) }

const Default_ScriptObject_Name string = "main"

func init() {
}
