// Code generated by protoc-gen-go from "tritium.proto"
// DO NOT EDIT!

package tritium

import proto "goprotobuf.googlecode.com/hg/proto"
import "math"
import "os"

// Reference proto, math & os imports to suppress error if they are not otherwise used.
var _ = proto.GetString
var _ = math.Inf
var _ os.Error

type Executable struct {
	Objects          []*ScriptObject `protobuf:"bytes,1,rep,name=objects" json:"objects,omitempty"`
	Pkg              *Package        `protobuf:"bytes,2,req,name=pkg" json:"pkg,omitempty"`
	XXX_unrecognized []byte          `json:",omitempty"`
}

func (this *Executable) Reset()         { *this = Executable{} }
func (this *Executable) String() string { return proto.CompactTextString(this) }

type BlitzSlug struct {
	Transformers     []*Executable `protobuf:"bytes,1,rep,name=transformers" json:"transformers,omitempty"`
	XXX_unrecognized []byte        `json:",omitempty"`
}

func (this *BlitzSlug) Reset()         { *this = BlitzSlug{} }
func (this *BlitzSlug) String() string { return proto.CompactTextString(this) }

func init() {
}
