// Code generated by protoc-gen-go from "tritium.proto"
// DO NOT EDIT!

package tritium

import proto "goprotobuf.googlecode.com/hg/proto"
import "math"
import "os"

// Reference proto, math & os imports to suppress error if they are not otherwise used.
var _ = proto.GetString
var _ = math.Inf
var _ os.Error

type Transform struct {
	Objects          []*ScriptObject `protobuf:"bytes,1,rep,name=objects" json:"objects"`
	Pkg              *Package        `protobuf:"bytes,2,req,name=pkg" json:"pkg"`
	XXX_unrecognized []byte
}

func (this *Transform) Reset()         { *this = Transform{} }
func (this *Transform) String() string { return proto.CompactTextString(this) }

type Slug struct {
	Transformers     []*Transform `protobuf:"bytes,1,rep,name=transformers" json:"transformers"`
	XXX_unrecognized []byte
}

func (this *Slug) Reset()         { *this = Slug{} }
func (this *Slug) String() string { return proto.CompactTextString(this) }

func init() {
}
