// Code generated by protoc-gen-go.
// source: object.proto
// DO NOT EDIT!

package proto

import proto1 "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto1.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type ScriptObject struct {
	Root             *Instruction `protobuf:"bytes,2,opt,name=root" json:"root,omitempty"`
	ScopeTypeId      *int32       `protobuf:"varint,4,opt,name=scope_type_id" json:"scope_type_id,omitempty"`
	Module           *string      `protobuf:"bytes,6,opt,name=module" json:"module,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ScriptObject) Reset()         { *m = ScriptObject{} }
func (m *ScriptObject) String() string { return proto1.CompactTextString(m) }
func (*ScriptObject) ProtoMessage()    {}

func (m *ScriptObject) GetRoot() *Instruction {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *ScriptObject) GetScopeTypeId() int32 {
	if m != nil && m.ScopeTypeId != nil {
		return *m.ScopeTypeId
	}
	return 0
}

func (m *ScriptObject) GetModule() string {
	if m != nil && m.Module != nil {
		return *m.Module
	}
	return ""
}

func init() {
}
