// Code generated by protoc-gen-go.
// source: object.proto
// DO NOT EDIT!

package proto

import proto1 "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = math.Inf

// Object representing a script
// Possibly linked or not
type ScriptObject struct {
	// optional string name = 1 [default='main'];
	Root *Instruction `protobuf:"bytes,2,opt,name=root" json:"root,omitempty"`
	// repeated Function functions = 3;
	ScopeTypeId *int32 `protobuf:"varint,4,opt,name=scope_type_id" json:"scope_type_id,omitempty"`
	// optional bool linked = 5;
	Module           *string `protobuf:"bytes,6,opt,name=module" json:"module,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ScriptObject) Reset()         { *m = ScriptObject{} }
func (m *ScriptObject) String() string { return proto1.CompactTextString(m) }
func (*ScriptObject) ProtoMessage()    {}

func (m *ScriptObject) GetRoot() *Instruction {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *ScriptObject) GetScopeTypeId() int32 {
	if m != nil && m.ScopeTypeId != nil {
		return *m.ScopeTypeId
	}
	return 0
}

func (m *ScriptObject) GetModule() string {
	if m != nil && m.Module != nil {
		return *m.Module
	}
	return ""
}

func init() {
}
