// Code generated by protoc-gen-go.
// source: rewrite_rule.proto
// DO NOT EDIT!

package proto

import proto1 "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto1.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type RewriteRule struct {
	Proxy            *string `protobuf:"bytes,1,opt,name=proxy" json:"proxy,omitempty"`
	Upstream         *string `protobuf:"bytes,2,opt,name=upstream" json:"upstream,omitempty"`
	Direction        *int32  `protobuf:"varint,3,opt,name=direction,def=0" json:"direction,omitempty"`
	CookieDomain     *string `protobuf:"bytes,4,opt,name=cookie_domain" json:"cookie_domain,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RewriteRule) Reset()         { *m = RewriteRule{} }
func (m *RewriteRule) String() string { return proto1.CompactTextString(m) }
func (*RewriteRule) ProtoMessage()    {}

const Default_RewriteRule_Direction int32 = 0

func (m *RewriteRule) GetProxy() string {
	if m != nil && m.Proxy != nil {
		return *m.Proxy
	}
	return ""
}

func (m *RewriteRule) GetUpstream() string {
	if m != nil && m.Upstream != nil {
		return *m.Upstream
	}
	return ""
}

func (m *RewriteRule) GetDirection() int32 {
	if m != nil && m.Direction != nil {
		return *m.Direction
	}
	return Default_RewriteRule_Direction
}

func (m *RewriteRule) GetCookieDomain() string {
	if m != nil && m.CookieDomain != nil {
		return *m.CookieDomain
	}
	return ""
}

func init() {
}
